server.port=8443

spring.application.name=lets-play

spring.data.mongodb.uri=mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:27017/${DB_NAME}?authSource=admin
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.data.mongodb.core.index=DEBUG

server.servlet.context-path=/api

server.ssl.key-store=classpath:springboot.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
server.ssl.key-password=${SSL_PASSWORD}